const mongoose=require('mongoose')
require('dotenv').config()
mongoose.connect(process.env.REACT_APP_MONGO_URL,{useNewUrlParser:true,useUnifiedTopology:true})
.then(()=>console.log('db connected'))
.catch((e)=>console.log('error',e))